# create dogs
puts 'seeding'
Pet.create(name: "Buddy", animal_type: "Dog", breed: "Golden Retriever", age: 2, gender: "Male", size: "Large", weight: 70, color: "Golden", image_url: "https://images.dog.ceo/breeds/retriever-golden/n02099601_7235.jpg", description: "Friendly and outgoing", available_for_adoption: true,user_id:29)
Pet.create(name: "Lucy", animal_type: "Dog", breed: "Labrador Retriever", age: 3, gender: "Female", size: "Medium", weight: 55, color: "Black", image_url: "https://images.dog.ceo/breeds/labrador/n02099712_3084.jpg", description: "Loves to play fetch", available_for_adoption: true,user_id:29)
Pet.create(name: "Max", animal_type: "Dog", breed: "German Shepherd", age: 4, gender: "Male", size: "Large", weight: 80, color: "Black and Tan", image_url: "https://images.dog.ceo/breeds/germanshepherd/n02106662_5134.jpg", description: "Intelligent and loyal", available_for_adoption: true,user_id:30)
Pet.create(name: "Charlie", animal_type: "Dog", breed: "Poodle", age: 4, gender: "Male", size: "Small", weight: 12, color: "White", image_url: "https://images.dog.ceo/breeds/poodle-miniature/n02113799_1536.jpg", description: "Friendly and playful", available_for_adoption: true,user_id:29)
Pet.create(name: "Daisy", animal_type: "Dog", breed: "Beagle", age: 2, gender: "Female", size: "Medium", weight: 20, color: "Brown and White", image_url: "https://images.dog.ceo/breeds/beagle/n02088364_952.jpg", description: "Sweet and affectionate", available_for_adoption: true,user_id:28)
Pet.create(name: "Rocky", animal_type: "Dog", breed: "Bulldog", age: 3, gender: "Male", size: "Large", weight: 60, color: "White and Brown", image_url: "https://images.dog.ceo/breeds/bulldog-french/n02108915_5065.jpg", description: "Charming and loyal", available_for_adoption: true,user_id:30)
Pet.create(name: "Bella", animal_type: "Dog", breed: "Chihuahua", age: 1, gender: "Female", size: "Small", weight: 6, color: "Brown", image_url: "https://images.dog.ceo/breeds/chihuahua/n02085620_2278.jpg", description: "Cute and sassy", available_for_adoption: true,user_id:30)
Pet.create(name: "Zeus", animal_type: "Dog", breed: "Great Dane", age: 2, gender: "Male", size: "Extra Large", weight: 120, color: "Black", image_url: "https://images.dog.ceo/breeds/dane-great/n02109047_7971.jpg", description: "Gentle giant", available_for_adoption: true,user_id:28)
Pet.create(name: "Molly", animal_type: "Dog", breed: "Boxer", age: 3, gender: "Female", size: "Large", weight: 55, color: "Brindle", image_url: "https://images.dog.ceo/breeds/boxer/n02108089_6466.jpg", description: "Energetic and loving", available_for_adoption: true,user_id:30)
# create cats
Pet.create(name: "Oliver", animal_type: "Cat", breed: "Domestic Shorthair", age: 1, gender: "Male", size: "Small", weight: 9, color: "Orange and White", image_url: "https://cdn2.thecatapi.com/images/0J-vPzVVW.jpg", description: "Affectionate and playful", available_for_adoption: true,user_id:29)
Pet.create(name: "Luna", animal_type: "Cat", breed: "Siamese", age: 2, gender: "Female", size: "Small", weight: 8, color: "Seal Point", image_url: "https://cdn2.thecatapi.com/images/2bg.jpg", description: "Energetic and talkative", available_for_adoption: true,user_id:26)
Pet.create(name: "Simba", animal_type: "Cat", breed: "Maine Coon", age: 3, gender: "Male", size: "Large", weight: 18, color: "Brown Tabby", image_url: "https://cdn2.thecatapi.com/images/b1p.jpg", description: "Gentle and friendly", available_for_adoption: true,user_id:24)
Pet.create(name: "Toby", animal_type: "Cat", breed: "British Shorthair", age: 1, gender: "Male", size: "Small", weight: 7, color: "Grey", image_url: "https://cdn2.thecatapi.com/images/35a.jpg", description: "Independent and intelligent", available_for_adoption: true,user_id:29)
Pet.create(name: "Lucky", animal_type: "Cat", breed: "Persian", age: 2, gender: "Female", size: "Small", weight: 6, color: "White", image_url: "https://cdn2.thecatapi.com/images/AjK2YfS8S.jpg", description: "Gentle and affectionate", available_for_adoption: true,user_id:30)
Pet.create(name: "Maximus", animal_type: "Cat", breed: "Sphynx", age: 3, gender: "Male", size: "Small", weight: 8, color: "Pink", image_url: "https://cdn2.thecatapi.com/images/AjK2YfS8S.jpg", description: "Gentle and affectionate", available_for_adoption: true,user_id:30)
# create rabbits
Pet.create(name: "Bugs", animal_type: "Rabbit", breed: "Holland Lop", age: 1, gender: "Male", size: "Small", weight: 3, color: "Brown", image_url: "https://i.pinimg.com/736x/1e/b0/44/1eb044fae4e0844f554e72e0b95b3598.jpg", description: "Cuddly and curious", available_for_adoption: true, user_id:30)
Pet.create(name: "Thumper", animal_type: "Rabbit", breed: "Mini Lop", age: 2, gender: "Female", size: "Small", weight: 4, color: "Grey", image_url: "https://www.pdsa.org.uk/media/6688/new-rabbit-banner.jpg?anchor=center&mode=crop&width=767&height=431&rnd=132456789000000000", description: "Playful and gentle", available_for_adoption: true, user_id:30)
 puts 'ended seeding'